"""delete coloumn sku

Revision ID: 882ff4e71b69
Revises: 2f3c30fbc658
Create Date: 2026-02-18 13:00:29.013513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '882ff4e71b69'
down_revision: Union[str, Sequence[str], None] = '2f3c30fbc658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_column('product', 'sku')
    op.drop_column('product', 'min_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('min_stock', sa.INTEGER(), nullable=False))
    op.add_column('product', sa.Column('sku', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=1)
    # ### end Alembic commands ###
